version: "3"

services: 
    api: 
        container_name: pizzapp_back
        restart: on-failure:10
        build: .
        ports:
            - "3001:4000"
        links: 
            - mongo
        volumes: 
            - .:/usr/src/app
    mongo: 
        container_name: pizzapp_database
        image: mongo
        ports: 
            - "27018:27017"
        logging: 
            driver: none
